version: '3'
services:
  python_devc:
    image: python_devc
    build:
        context: python_devc
        dockerfile: Dockerfile
    # コンテナ内のユーザーIDとグループIDを指定
        args:
            USER_UID: ${UID}
            USER_GID: ${GID}
    user: "${UID}:${GID}"
    #restart: always
    environment:
      TZ: ${TZ}
      UID: ${UID}
      GID: ${GID}
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONPYCACHEPREFIX: "/tmp"
    volumes:
      - ./python_devc/src:/usr/src/
