# Yarnインストールコンテナ
FROM node:24-trixie-slim
LABEL maintaner='y-yoshimoto'
# 作業ディレクトリ名指定
ARG WORKDIR_NAME=sfa_cli
# 環境変数を設定する
ENV NODE_ENV=development

# 必要なパッケージインストール
RUN --mount=type=cache,target=/var/cache/apt \
    --mount=type=cache,target=/var/lib/apt \
    apt-get update \
    && apt-get install -y curl jq openssl 

# 必要なパッケージをインストール
RUN npm install -g typescript \
    && npm install --global @salesforce/cli --force \
    && sf --version

# 実行ユーザー追加
ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=1000
RUN useradd -m -s /bin/bash -u $USER_UID -g $USER_GID $USERNAME || usermod -l $USERNAME node \
    && usermod -a -G $USER_GID $USERNAME
# アプリケーションのディレクトリ作成/権限変更
RUN mkdir -p /$WORKDIR_NAME \
    && chown -R $USERNAME:dialout /$WORKDIR_NAME/
# Initスクリプト設置
COPY docker-entrypoint_sfacli.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
# ユーザー変更/作業ディレクトリ変更
WORKDIR /$WORKDIR_NAME
CMD ["tail", "-f", "/dev/null"]