version: "3"
services:
  pyffmpeg:
    image: pyffmpeg
    build: .
    #restart: always
    environment:
      TZ: ${TZ}
      PYTHONDONTWRITEBYTECODE: 1
    volumes:
      - ./src/:/usr/src
  web:
    image: nginx:alpine
    restart: always
    ports:
      - 8045:80
    volumes:
      - ./src/files/:/usr/share/nginx/html/
    depends_on:
      - pyffmpeg
