services:
  api_pytest_c:
    image: api_pytest_c
    build: ./
    # restart: always
    volumes:
      - ./:/app/
    ports:
      - "8000:8000"
    user: "501:20"
    environment:
      TZ: Asia/Tokyo
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONPATH: /app/src
      PGPASSWORD: postgres
      # PLAYWRIGHT_BROWSERS_PATH: /home/vscode/pw-browsers
      
