version: "3"
services:
  fileio:
    image: fileio
    build: fileio
    #restart: always
    environment:
      TZ: ${TZ}
      PYTHONDONTWRITEBYTECODE: 1
    volumes:
      - ./fileio/src:/usr/src/
