# https://hub.docker.com/r/heartexlabs/label-studio
FROM python:3.10.5-slim-bullseye AS builder
LABEL maintaner='y-yoshimoto'

#CMD ["label-studio", "start", "--username", "test@test.com", "--password", "password"]