version: "3"
services:
  decodebase64:
    image: decodebase64
    build: decodebase64
    #restart: always
    environment:
      TZ: ${TZ}
      PYTHONDONTWRITEBYTECODE: 1
    volumes:
      - ./decodebase64/src:/usr/src/
